apiVersion: v2
name: maas-text-vision-gateway
description: Gateway API(Envoy Gateway), HTTPRoute, SecurityPolicy, Ingress for maas-text-vision-gateway
type: application
version: 0.1.0
appVersion: "1.0"
