apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: {{ .Values.referenceGrant.name }}
  namespace: {{ .Values.namespaces.model }}
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
  labels:
    {{- include "maas-text-vision-gateway.labels" . | nindent 4 }}
spec:
  from:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      namespace: {{ .Values.namespaces.gateway }}
    - group: gateway.envoyproxy.io
      kind: SecurityPolicy
      namespace: {{ .Values.namespaces.gateway }}
  to:
    - group: ""
      kind: Service
